### ISSUE TITLE
Multisite support

### ISSUE THREAD

**Issue by duncanmcclean** [doublethreedigital/guest-entries#14]
### What would you like to see added?

Currently, this addon doesn't support multi-site setups. It should generate the entry in the locale/site the user is currently in.

### Is there a workaround you can use in the meantime?

Do it yourself with a listener.

### Priority wise - where's this feature for you?

Nice to have

**Comment by remiduval** [comment]
Thanks!
Ok, for my use case, I'll stick with forcing the entry to be added to the English site and then creating its French version with the GuestEntryCreated event.
Does it mean I'll now have to pass a `site="english"` parameter? I couldn't find it in the docs
