### ISSUE TITLE
File upload goes to the wrong directory

### ISSUE THREAD

**Issue by maxwkfcc** [doublethreedigital/guest-entries#24]
### Bug Description

Hi Guest Entries,

We are trying to upload files according to the setup here.

https://statamic.com/addons/double-three-digital/guest-entries/docs

And I have specified an assets field pointing to the assets Container.

After upload, I expect it goes to /var/www/html/public/assets.

However, it goes to /var/www/html/public/assets/var/www/html/public/assets.

It just simply take the public assets folder as the root and create folders.

### Steps to reproduce

1. Create Assets Field in Collection Blueprint.
2. Set the Container as Assets
3. Submit the Guest Entry by following the file upload part stated in https://statamic.com/addons/double-three-digital/guest-entries/docs#file-uploads
4. Submit the form
5. Go to the corresponding collection entry that submitted
6. Browse the file and it creates `/var/www/html/public/assets` inside the original Assests directory.
7. You will find the uploaded file pointing to there

### Environment

Statamic 3.3.9 Pro
Laravel 8.78.1
PHP 8.1.5
doublethreedigital/guest-entries 1.2.0

**Comment by duncanmcclean** [comment]
Fixed in [v1.2.1](https://github.com/doublethreedigital/guest-entries/releases/tag/v1.2.1)
