### ISSUE TITLE
error and success messages not shown

### ISSUE THREAD

**Issue by wm-simon** [doublethreedigital/guest-entries#3]
### Description

The default antlers seems not to work and there is nothing about it in the docs.

### Environment

Statamic 3.2.1 Pro
Laravel 8.57.0
PHP 7.4.4
doublethreedigital/duplicator 1.3.4   
doublethreedigital/guest-entries 1.0.1

**Comment by duncanmcclean** [comment]
I've added some documentation around this and a tag for easier access. Essentially to display error messages, you can do something like this.

```
{{ guest-entries:errors }}
    <li>{{ value }}</li>
{{ /guest-entries:errors }}
```

If you want to also handle 'success messages', you can specify a redirect URL on the form, and add a query parameter which you can check in your template.

```antlers
{{ guest-entries:create redirect="/current-page?success=true" }}
    <!-- blah blah blah -->
{{ /guest-entries:create }}
```

```antlers
{{ if {get:success} }}
    <!-- your success message -->
{{ /if }}
```

---

FYI: you'll need to update to [v1.0.2](https://github.com/doublethreedigital/guest-entries/releases/tag/v1.0.2) for this to work.

**Comment by wm-simon** [comment]
Worked, thank you!
