### ISSUE TITLE
Add support for revisions

### ISSUE THREAD

**Issue by wm-simon** [doublethreedigital/guest-entries#4]
### What would you like to see added?

When a guest edits the entry, the changes should not shown directly public. At first the moderator should be able take a look on it and publish the changes after it.

### Is there a workaround you can use in the meantime?

Nope

### Priority wise - where's this feature for you?

This is sort of a blocker for me/this project.

**Comment by duncanmcclean** [comment]
I've never used Revisions before so I'll need to take a look when I have some more time to dig in. I'm not quite sure how it works under the hood and whether it's an easy-ish thing to support.

**Comment by duncanmcclean** [comment]
Released in [v1.0.4](https://github.com/doublethreedigital/guest-entries/releases/tag/v1.0.4)
